CREATE TABLE Libro(
    titulo    VARCHAR(20) NOT NULL,
    autor     VARCHAR(15) NOT NULL,
    editorial VARCHAR(15) NOT NULL);
    
INSERT INTO Libro VALUES('LA ILIADA','HOMERO','PORRUA');
INSERT INTO Libro VALUES('LA ODISEA','HOMERO','PORRUA');
INSERT INTO Libro VALUES('COSMOS','SAGAN CARL','PLANETA');
INSERT INTO Libro VALUES('LOCAL NETWORKS','STALLINS','PEARSON');
INSERT INTO Libro VALUES('FISICA','RESNICK','CECSA');
INSERT INTO Libro VALUES('TERMICA','SONTAG','CECSA');